# Generated by Django 6.0.1 on 2026-02-11 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_user',
            field=models.ForeignKey(blank=True, help_text='Optional portal account for guardians/parents.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
