# Generated by Django 6.0.1 on 2026-03-20 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_assessment_grade'),
        ('students', '0002_student_guardian_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='current_classroom',
            field=models.ForeignKey(blank=True, help_text='Current primary classroom/section.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.classroom'),
        ),
    ]
