# Generated by Django 5.2 on 2026-03-11 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0003_assessment_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('HOLIDAY', 'Holiday'), ('EXAM', 'Exam'), ('SPORTS', 'Sports Event'), ('CULTURAL', 'Cultural Event'), ('MEETING', 'Meeting'), ('WORKSHOP', 'Workshop'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('all_school', models.BooleanField(default=True, help_text='Event for entire school')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('target_classrooms', models.ManyToManyField(blank=True, help_text='Specific classes for this event', related_name='events', to='academics.classroom')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['start_date', 'end_date'], name='calendar_ev_start_d_d748d9_idx'), models.Index(fields=['event_type'], name='calendar_ev_event_t_4d7e8f_idx')],
            },
        ),
    ]
