# Generated by Django 6.0.1 on 2026-02-16 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staff'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('GUARDIAN', 'Guardian / Parent')], default='STAFF', max_length=20),
        ),
    ]
