# Generated by Django 5.2 on 2026-03-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_a972ce_idx',
            old_name='notificatio_recipie_8c9e5d_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_4e3567_idx',
            old_name='notificatio_recipie_0e1a8f_idx',
        ),
    ]
