# Generated by Django 6.0.1 on 2026-03-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template name for easy identification', max_length=120)),
                ('description', models.TextField(blank=True, help_text='Optional description of this report template')),
                ('fields', models.JSONField(default=list, help_text='List of field names to include in the report')),
                ('filters', models.JSONField(default=dict, help_text='Default filter values (date_from, date_to, classroom_id, etc.)')),
                ('grouping', models.CharField(blank=True, choices=[('NONE', 'No Grouping'), ('STUDENT', 'By Student'), ('CLASSROOM', 'By Classroom'), ('SUBJECT', 'By Subject'), ('DATE', 'By Date')], default='NONE', max_length=20)),
                ('sorting', models.CharField(choices=[('DATE_ASC', 'Date (Oldest First)'), ('DATE_DESC', 'Date (Newest First)'), ('STUDENT_ASC', 'Student Name (A-Z)'), ('STUDENT_DESC', 'Student Name (Z-A)'), ('STATUS_ASC', 'Status (A-Z)'), ('STATUS_DESC', 'Status (Z-A)')], default='DATE_DESC', max_length=20)),
                ('is_shared', models.BooleanField(default=False, help_text='Allow other admin users to use this template')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_by', '-created_at'], name='attendance__created_2bde84_idx')],
            },
        ),
    ]
