# Generated by Django 5.2 on 2026-04-14 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_emaillog_notificationpreference"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancerecord",
            name="digest_sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
